version: '2'
services:
  mariadb:
    image: mariadb:10.1
    command: mysqld --innodb-buffer-pool-size=64M
    volumes:
      - "./mariadb:/var/lib/mysql"
#      - "./dump.sql:/tmp/dump.sql"
    restart: always
#    ports:
#      - "43301:3306"
    env_file:
      - "./mariadb.env"
  wordpress:
    depends_on:
      - mariadb
    image: wordpress:latest
    links:
      - mariadb
    volumes:
      - "./upload_size.ini:/usr/local/etc/php/conf.d/upload_size.ini"
      - "./themes:/var/www/html/wp-content/themes"
      - "./uploads:/var/www/html/wp-content/uploads"
      - "./plugins:/var/www/html/wp-content/plugins"
    ports:
      - "42081:80"
      - "42441:443"
    restart: always
    env_file:
      - "./wordpress.env"
